# Generated by Django 3.2 on 2021-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210629_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.CharField(default='', max_length=600),
        ),
    ]
