# Generated by Django 3.2 on 2021-06-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_keyword_post_keywords_seperatebyspaces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uniqueVisitor',
        ),
        migrations.AddField(
            model_name='post',
            name='uniqueVisitorIPs',
            field=models.TextField(default=''),
        ),
    ]
