# Generated by Django 3.2 on 2021-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210630_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords_seperateBySpaces',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='uniqueVisitorIPs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
