# Generated by Django 3.2 on 2021-07-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_keywords_seperatebyspaces_post_keywords_seperatebycommaspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metaDesc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
