# Generated by Django 3.2 on 2021-07-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_metadesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='metaDesc',
            new_name='metaDesc_min130Chars_max170Chars',
        ),
    ]
