# Generated by Django 3.2 on 2021-07-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_keywords_seperatebycommaspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords_seperateByCommaSpace',
            field=models.CharField(default='', help_text="Seperate by Comma and space (', ')", max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='metaDesc_min130Chars_max170Chars',
            field=models.CharField(help_text='min: 130 letters, max: 170 letters', max_length=200),
        ),
    ]
