# Generated by Django 3.2 on 2021-07-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210721_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keywords_seperateByCommaSpace',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='metaDesc_min130Chars_max170Chars',
            new_name='metaDesc',
        ),
    ]
