# Generated by Django 3.2 on 2021-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210721_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorLink',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
