# Generated by Django 3.2 on 2021-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_authorlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorLink',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
