# Generated by Django 3.2 on 2021-04-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('nameAndDesignation', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=355)),
            ],
        ),
    ]
