# Generated by Django 3.2 on 2021-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=355)),
                ('desc', models.TextField()),
                ('projectInfo', models.TextField()),
                ('img1', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img2', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img3', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img4', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img5', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img6', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img7', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img8', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img9', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
                ('img10', models.ImageField(upload_to='home/portfolio/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
