# Generated by Django 3.2 on 2021-04-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210421_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img1',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img10',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img2',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img3',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img4',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img5',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img6',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img7',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img8',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img9',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
    ]
