# Generated by Django 3.2 on 2021-04-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sno',
            field=models.IntegerField(default=1),
        ),
    ]
