# Generated by Django 3.2 on 2021-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_portfolio_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='featureImage',
            field=models.ImageField(blank=True, upload_to='home/portfolio'),
        ),
    ]
