# Generated by Django 3.2 on 2021-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_portfolio_featureimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_644x641px', models.ImageField(upload_to='home/our_team')),
                ('name', models.CharField(max_length=400)),
                ('designation', models.CharField(max_length=400)),
            ],
        ),
    ]
