# Generated by Django 3.2 on 2021-05-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='id',
        ),
        migrations.AddField(
            model_name='teammember',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
