# Generated by Django 3.2 on 2021-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210525_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='metaDesc_min130Chars_max170Chars',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
