# Generated by Django 3.2 on 2021-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_portfolio_metadesc_min130chars_max170chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='keywords_seperateByCommaSpace',
            field=models.CharField(default='', max_length=600),
        ),
    ]
