# Generated by Django 3.2 on 2021-07-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_portfolio_keywords_seperatebycommaspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo_644x641px',
            field=models.ImageField(help_text='644x641px', upload_to='home/our_team'),
        ),
    ]
