# Generated by Django 3.2 on 2021-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_teammember_photo_644x641px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='metaDesc_min130Chars_max170Chars',
            field=models.CharField(help_text='min: 130 letters, max: 170 letters', max_length=200),
        ),
    ]
