# Generated by Django 3.2 on 2021-07-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_portfolio_metadesc_min130chars_max170chars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='photo_644x641px',
            new_name='photo',
        ),
    ]
