# Generated by Django 3.2 on 2021-07-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_metadesc_min130chars_max170chars_portfolio_metadesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='keywords_seperateByCommaSpace',
            new_name='keywords',
        ),
    ]
