# Generated by Django 3.2 on 2021-07-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_keywords_seperatebycommaspace_portfolio_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(height_field=641, help_text='644x641px', upload_to='home/our_team', width_field=644),
        ),
    ]
