# Generated by Django 3.2 on 2021-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(help_text='644x641px', upload_to='home/our_team'),
        ),
    ]
