# Generated by Django 3.2 on 2021-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210721_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='photo_width',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(help_text='644x641px', upload_to='home/our_team'),
        ),
    ]
