# Generated by Django 3.2 on 2021-07-21 09:21

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210721_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img1',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img10',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img2',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img3',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img4',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img5',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img6',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img7',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img8',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img9',
            field=models.ImageField(blank=True, help_text='300x300px', upload_to='home/portfolio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', help_text='644x641px', keep_meta=True, quality=0, size=[644, 641], upload_to='home/our_team'),
        ),
    ]
