# Generated by Django 3.2 on 2021-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210721_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img1',
            field=models.ImageField(help_text='300x300px', upload_to='home/portfolio'),
        ),
    ]
