# Generated by Django 3.2 on 2021-08-15 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_broadcasted_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasted_message',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
