# Generated by Django 3.2 on 2021-08-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_broadcasted_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasted_message',
            name='activeDays',
            field=models.IntegerField(default=2, help_text='The no. of days for which the message should be shown.'),
            preserve_default=False,
        ),
    ]
