# Generated by Django 3.2.8 on 2021-11-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_broadcasted_message_activedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(height_field='myHeight', help_text='644x641px', upload_to='home/our_team', width_field='myWidth'),
        ),
    ]
