# Generated by Django 3.2.8 on 2021-11-21 05:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', help_text='644x641px', keep_meta=True, quality=0, size=[644, 641], upload_to='home/our_team'),
        ),
    ]
