# Generated by Django 3.2.8 on 2021-11-21 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
